/** SHS tracks/strands (K-12), incl. the strengthened-SHS track names. */
export const SHS_STRANDS = [
  'STEM',
  'ABM',
  'HUMSS',
  'GAS',
  'TVL - ICT',
  'TVL - Home Economics',
  'TVL - Industrial Arts',
  'TVL - Agri-Fishery Arts',
  'Sports',
  'Arts and Design',
  'Academic Track',
  'Technical-Professional Track',
] as const;

export const MAJOR_OPTIONS = [
  'Computer Science',
  'Information Technology',
  'Computer Engineering',
  'Civil Engineering',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Nursing',
  'Medical Technology',
  'Pharmacy',
  'Psychology',
  'Accountancy',
  'Business Administration',
  'Hospitality Management',
  'Tourism Management',
  'Education',
  'Communication',
  'Political Science',
  'Architecture',
  'Fine Arts',
  'Biology',
  'Criminology',
] as const;

export const INTEREST_OPTIONS = [
  'Technology',
  'Business',
  'Arts',
  'Science',
  'Engineering',
  'Health',
  'Design',
  'Law',
  'Education',
  'Media',
  'Sports',
  'Public Service',
] as const;
