import { StyleSheet } from 'react-native';

import { fontSize, fontWeight, radius, spacing, TOUCH_TARGET, type ThemeColors } from '@/styles';

export const createStyles = (c: ThemeColors) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: c.background },
    list: { flex: 1 },
    listContent: { padding: spacing.md, gap: spacing.sm, flexGrow: 1 },
    bubbleRow: { flexDirection: 'row' },
    mineRow: { justifyContent: 'flex-end' },
    bubble: {
      maxWidth: '82%',
      gap: spacing.xs,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.md,
      borderRadius: radius.lg,
    },
    mine: { backgroundColor: c.primary, borderBottomRightRadius: radius.sm },
    theirs: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      borderBottomLeftRadius: radius.sm,
    },
    failed: { opacity: 0.6 },
    body: { fontSize: fontSize.md, color: c.text },
    bodyMine: { color: c.onPrimary },
    time: { fontSize: fontSize.xs, color: c.textMuted, alignSelf: 'flex-end' },
    timeMine: { color: c.onPrimary, opacity: 0.8 },
    error: { fontSize: fontSize.xs, color: c.danger, alignSelf: 'flex-end' },
    attachment: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      minHeight: TOUCH_TARGET,
      padding: spacing.sm,
      borderRadius: radius.md,
      backgroundColor: c.background,
    },
    attachmentText: { flex: 1, gap: 2 },
    attachmentName: { fontSize: fontSize.sm, fontWeight: fontWeight.medium, color: c.text },
    attachmentStatus: { fontSize: fontSize.xs, color: c.textMuted },
    blocked: { color: c.danger },
    composer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: spacing.xs,
      padding: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: c.border,
      backgroundColor: c.surface,
    },
    input: {
      flex: 1,
      minHeight: TOUCH_TARGET,
      maxHeight: 140,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      fontSize: fontSize.md,
    },
    iconButton: {
      width: TOUCH_TARGET,
      height: TOUCH_TARGET,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: TOUCH_TARGET / 2,
    },
    sendButton: { backgroundColor: c.primary },
    disabled: { opacity: 0.4 },
    pending: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginHorizontal: spacing.sm,
      marginTop: spacing.sm,
      padding: spacing.sm,
      borderRadius: radius.md,
      backgroundColor: c.background,
      borderWidth: 1,
      borderColor: c.border,
    },
    notice: {
      fontSize: fontSize.xs,
      color: c.textMuted,
      textAlign: 'center',
      paddingHorizontal: spacing.md,
      paddingTop: spacing.xs,
    },
  });
